title: 法喜个人主页
description: 云与禅

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
