#!/usr/bin/env python3
"""Sync the GTM shift-log with real cases from the kuba incident database.

Reads curated incident files (Markdown + YAML frontmatter) from a local
checkout of https://github.com/kudig-io/kuba, extracts verified metadata
(id / title / company / date / severity), and regenerates the log rows
between the log:sync sentinels in index.html. Re-run after kuba updates,
then re-deploy.
"""

from __future__ import annotations

import argparse
import html
import os
import re
import sys
from pathlib import Path

KUBA_REPO_URL = "https://github.com/kudig-io/kuba"
KUBA_DEFAULT_PATHS = (
    Path.home() / "Documents/GitHub/kudig-io/kuba",
    Path(__file__).resolve().parent.parent / "kuba",
)

SENTINEL_START = "<!-- log:sync:start · generated by sync_log.py from kuba-database; do not edit by hand -->"
SENTINEL_END = "<!-- log:sync:end -->"

# view: which four-perspective lens the entry foregrounds (FDE = data & evidence,
# SA = relationship & architecture). en/req_en/req_zh are editorial glosses;
# every factual field (date/company/id/severity/title) comes from kuba itself.
ENTRIES: list[dict] = [
    {
        "relpath": "incidents/saas-platforms/2015-05-28-ctrip-code-deletion.md",
        "view": "FDE",
        "label": "PHASE 12 · RUNBOOK",
        "en": "Production code deleted by hand on a busy evening; recovery ran all night on improvised steps.",
        "req_en": "rollback and safe failure modes defined before launch.",
        "req_zh": "回滚路径与安全失败模式，先于上线存在。",
    },
    {
        "relpath": "incidents/cloud-infrastructure/2022-12-18-aliyun-hongkong-outage.md",
        "view": "FDE",
        "label": "GATE fat_sat",
        "en": "A chilled-water air lock plus group-control deadlock took a whole availability zone down for over 10 hours.",
        "req_en": "cooling and control interlocks pass on-site acceptance before launch.",
        "req_zh": "冷却与群控联动必须通过现场验收，才能放行上线。",
    },
    {
        "relpath": "incidents/sa-architecture/2025-09-18-clerk-database-incident.md",
        "view": "FDE",
        "label": "GATE slo",
        "en": "A vendor auto-upgrade stormed connection pools for 4 days; monitoring sampling hid the diagnosis.",
        "req_en": "error budget + alert route; evidence that sampling cannot mask.",
        "req_zh": "错误预算 + 告警路由；采样不能掩盖证据。",
    },
    {
        "relpath": "incidents/sa-architecture/2025-06-26-clerk-cloudrun-outage.md",
        "view": "SA",
        "label": "PHASE 07 · REAL DATA",
        "en": "Single-region auth trusted the vendor's redundancy promise; one regional failure logged out every customer for 45 minutes.",
        "req_en": "vendor promises are not verified facts; prove it on production-shaped reality.",
        "req_zh": "供应商承诺不等于已验证事实，用生产形态的真实环境验证。",
    },
    {
        "relpath": "incidents/sa-architecture/2023-09-12-unity-runtime-fee.md",
        "view": "SA",
        "label": "GATE success_criteria",
        "en": "An install-fee decision shipped without stakeholder alignment; the ecosystem revolted, the CEO left, the policy died.",
        "req_en": "written criteria + ≥ 2 sponsors + aligned success metrics.",
        "req_zh": "书面标准 + ≥2 发起人 + 干系人对齐的成功指标。",
    },
    {
        "relpath": "incidents/networking-dns/2021-10-04-facebook-bgp.md",
        "view": "SA",
        "label": "PHASE 12 · RUNBOOK",
        "en": "A maintenance command withdrew every BGP route; engineers were locked out of the very building holding the recovery tools.",
        "req_en": "an out-of-band recovery path that was rehearsed, not assumed.",
        "req_zh": "带外恢复路径要演练过，不能假设它在。",
    },
]

FIELDS = ("id", "title", "company", "date", "severity")


def resolve_kuba(explicit: str | None) -> Path:
    candidates = [Path(explicit)] if explicit else []
    env = os.environ.get("KUBA_DB")
    if env:
        candidates.append(Path(env))
    candidates.extend(KUBA_DEFAULT_PATHS)
    for path in candidates:
        if (path / "incidents").is_dir():
            return path
    tried = ", ".join(str(c) for c in candidates)
    sys.exit(f"kuba checkout not found (tried: {tried}); pass --kuba <path>")


def parse_frontmatter(text: str) -> dict:
    match = re.match(r"\A---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        sys.exit("frontmatter block not found")
    meta = {}
    for line in match.group(1).splitlines():
        field = re.match(r"^(id|title|company|date|severity):\s*(.+?)\s*$", line)
        if field:
            meta[field.group(1)] = field.group(2)
    missing = [f for f in FIELDS if f not in meta]
    if missing:
        sys.exit(f"frontmatter missing fields: {missing}")
    return meta


def build_row(entry: dict, meta: dict) -> str:
    esc = html.escape
    date = meta["date"].replace("-", "·")
    view = entry["view"]
    url = f"{KUBA_REPO_URL}/blob/main/{entry['relpath']}"
    return (
        f'      <div class="log-row slot">\n'
        f'        <div class="log-time">{esc(date)}'
        f'<span class="log-view view-{view.lower()}">{view}</span>'
        f"<small>{esc(meta['id'])} · {esc(meta['severity'])}</small></div>\n"
        f'        <p class="log-entry">{esc(entry["en"])}'
        f'<span class="zh" lang="zh">{esc(meta["title"])}</span></p>\n'
        f'        <div class="log-catch"><b>{esc(view)} · {esc(entry["label"])}</b>: {esc(entry["req_en"])}'
        f'<span class="zh" lang="zh">{esc(entry["req_zh"])}</span>'
        f'<a class="log-src" href="{url}" target="_blank" rel="noopener">CASE FILE ↗ {esc(meta["company"])}</a></div>\n'
        f"      </div>"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kuba", help="path to kuba checkout")
    parser.add_argument("--page", type=Path, default=Path(__file__).resolve().parent / "index.html")
    args = parser.parse_args()

    kuba = resolve_kuba(args.kuba)
    rows = []
    for entry in ENTRIES:
        path = kuba / entry["relpath"]
        if not path.is_file():
            sys.exit(f"incident file missing: {path}")
        meta = parse_frontmatter(path.read_text(encoding="utf-8"))
        rows.append(build_row(entry, meta))
        print(f"  {meta['date']}  {meta['id']:<28} {meta['severity']:<6} {meta['company']}")

    page = args.page.read_text(encoding="utf-8")
    block = f"{SENTINEL_START}\n" + "\n".join(rows) + f"\n{SENTINEL_END}"
    new_page, count = re.subn(
        re.escape(SENTINEL_START) + r".*?" + re.escape(SENTINEL_END),
        lambda _: block,
        page,
        flags=re.DOTALL,
    )
    if count != 1:
        sys.exit(f"expected exactly one sentinel pair in {args.page}, found {count}")
    args.page.write_text(new_page, encoding="utf-8")
    print(f"synced {len(rows)} entries into {args.page}")


if __name__ == "__main__":
    main()
